# Generated by Django 3.1.7 on 2021-03-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created', verbose_name='created')),
                ('book', models.ForeignKey(help_text='book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_books', to='books.book', verbose_name='book')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_books', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved_book',
                'verbose_name_plural': 'saved_books',
                'db_table': 'books.saved_books',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('text', models.TextField(help_text='text', verbose_name='text')),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='rating', max_digits=1, verbose_name='rating')),
                ('book', models.ForeignKey(help_text='book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='books.book', verbose_name='book')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'db_table': 'books.reviews',
            },
        ),
        migrations.CreateModel(
            name='RentedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created', verbose_name='created')),
                ('state', models.CharField(default='reading', help_text='state', max_length=32, verbose_name='state')),
                ('book', models.ForeignKey(help_text='book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to='books.book', verbose_name='book')),
                ('user', models.ForeignKey(help_text='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'rented_book',
                'verbose_name_plural': 'rented_books',
                'db_table': 'books.rented_books',
            },
        ),
    ]
