# Generated by Django 3.1.7 on 2021-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rentedbook_review_savedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbook',
            name='term',
            field=models.IntegerField(default=0, help_text='term', verbose_name='term'),
        ),
    ]
