# Generated by Django 3.1.7 on 2021-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rentedbook_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='russian', help_text='language', max_length=32, verbose_name='language'),
        ),
    ]
