image: docker-proxy.choco.kz/docker:20.10.0
stages:
  - containerize
  - release

include:
  - project: 'templates/ci'
    file: 'containerize/docker-build.yml'

variables:
  POSTGRES_DB: db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  RABBITMQ_DEFAULT_VHOST: vhost
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: pass

.release: &release
  stage: release
  tags:
    - docker
  image: ${RELEASE_IMAGE}
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release -a oqytoqy django
