# Generated by Django 3.0.8 on 2020-08-01 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, help_text='created_at',
                        verbose_name='created_at',
                    ),
                ),
                (
                    'modified_at',
                    models.DateTimeField(
                        auto_now=True, help_text='modified_at',
                        verbose_name='modified_at',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        help_text='user', related_name='profile',
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL, verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'profile', 'db_table': 'common.profiles',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
