name: '' #set whatevername you want to your github job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: 'dina.yestemir@gmail.com'
          api_key: 'c851ff8a-abbf-41eb-9935-4aba5ba0c148'
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"appname":"oqytoqy","apptype":"web"}]'
